# Generated by Django 5.1.3 on 2025-01-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('nome_completo', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
    ]
