# Generated by Django 5.1.5 on 2025-01-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, editable=False, max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='logo_loja',
        ),
        migrations.AddField(
            model_name='user',
            name='login_com_email',
            field=models.BooleanField(default=False, verbose_name='login com email'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_num_links',
            field=models.PositiveIntegerField(default=10, verbose_name='max number of links'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_num_links_temporary',
            field=models.PositiveIntegerField(default=10, verbose_name='max number of temporary links'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', help_text='User role', max_length=10, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='user',
            name='verificar_email',
            field=models.BooleanField(default=False, verbose_name='email verificado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
