# Generated by Django 5.1.5 on 2025-01-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dav', '0002_token_remove_user_logo_loja_user_login_com_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='max_num_links',
        ),
        migrations.RemoveField(
            model_name='user',
            name='max_num_links_temporary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
