# Generated by Django 5.1.5 on 2025-02-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dav', '0002_remove_produtopromocao_promocao_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtopromocao',
            name='desconto',
            field=models.CharField(choices=[(5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25')], default=10, max_length=1),
        ),
        migrations.AddField(
            model_name='produtopromocao',
            name='expiracao_data',
            field=models.DateField(blank=True, help_text='escolha uma data dentro do limite definido', null=True),
        ),
        migrations.AddField(
            model_name='produtopromocao',
            name='limite_maximo',
            field=models.DateField(blank=True, help_text='defina até quando pode ser escolhida uma data de expiração', null=True),
        ),
    ]
