# Generated by Django 5.1.5 on 2025-02-01 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dav', '0006_alter_produtopromocao_desconto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data_venda',
        ),
        migrations.AlterField(
            model_name='produto',
            name='detalhes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(upload_to='imagem_promocao/')),
                ('desconto', models.DecimalField(decimal_places=2, help_text='Desconto em porcentagem (0-100)', max_digits=10)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='dav.produto')),
            ],
        ),
        migrations.DeleteModel(
            name='ProdutoPromocao',
        ),
    ]
