# Generated by Django 5.1.5 on 2025-02-01 20:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dav', '0007_remove_produto_data_venda_alter_produto_detalhes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='promocao',
            options={'verbose_name': 'Promoção', 'verbose_name_plural': 'Promoções'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='detalhes',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(help_text='Adicione uma imagem para o produto', upload_to='imagem_produto/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999999.99)], verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='data_fim',
            field=models.DateField(verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='desconto',
            field=models.DecimalField(decimal_places=2, help_text='Desconto em porcentagem (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='imagem',
            field=models.ImageField(upload_to='imagem_promocao/', verbose_name='Imagem da Promoção'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='dav.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
